<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-OM6DM447" failures="1" tests="6" name="checking" time="60.292" errors="0" timestamp="2024-08-25T00:47:39 IST">
  <testcase classname="AllureReport.TestCase2" name="testMethod2" time="0.088"/>
  <testcase classname="AllureReport.TestCase1" name="testMethod1" time="0.09">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at AllureReport.TestCase1.testMethod1(TestCase1.java:12)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testMethod1 -->
  <testcase classname="testNGLearn.NewTestClass" name="reachDashBoardPage" time="2.934"/>
  <testcase classname="testNGLearn.NewTestClass" name="validateDashboardPageContent" time="1.029"/>
  <testcase classname="testNGLearn.NewTestClass" name="validateTitle" time="0.018"/>
  <testcase classname="testNGLearn.NewTestClass" name="validateUrl" time="1.939"/>
</testsuite> <!-- checking -->
